package edu.abcd.smartphone.domain.model;

public enum TypeDisplayUI {
    TYPE_NOTIFICATION, TYPE_DEFAULT_SYSTEM, TYPE_LANGUAGE, TYPE_REMOVE_CACHE, HOT_LINE_PHONE, TYPE_VERSION, TYPE_PRIVACY, TYPE_SHARE, TYPE_OVERVIEW
}
